apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dmkqojut
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dmkqojut:5e7683810d8613ed3dadecceea61af51dbed62db@sha256:9a2178e779df4bf298eed0c4f3129ccefa380f11e7445e1b51a4eaebf2f5147e
          name: container-image
